name: BLUESPAWN client build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:

    strategy:
      matrix:
        buildtype: [Release, Debug]
        buildarch: [x64, x86]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Install vcpkg
      shell: powershell
      run: |
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install yara:${{ matrix.buildarch }}-windows-static
        .\vcpkg.exe integrate install
        cd ..

    - name: Download NuGet packages
      run: nuget restore BLUESPAWN.sln

    - name: Build BLUESPAWN-client
      run: |
        "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" BLUESPAWN.sln /p:Configuration=${{ matrix.buildtype }} /p:Platform=${{ matrix.buildarch }}
      shell: cmd

    - name: Set PowerShell Execution Policy
      run: powershell set-executionpolicy Unrestricted
      shell: powershell

    - name: Run BLUESPAWN Hunt
      run: artifacts\${{ matrix.buildarch }}\${{ matrix.buildtype }}\BLUESPAWN-client.exe --hunt -l Normal --log=xml --reaction=log
      shell: cmd

    - name: Rename BLUESPAWN XML output file
      run: Get-ChildItem "bluespawn*.xml" | Rename-Item -NewName BLUESPAWNHuntResults.xml
      shell: powershell

    - uses: actions/upload-artifact@master
      with:
        name: BLUESPAWN-client-${{ matrix.buildarch }}-${{ matrix.buildtype }}
        path: artifacts\${{ matrix.buildarch }}\${{ matrix.buildtype }}\BLUESPAWN-client.exe

    - uses: actions/upload-artifact@master
      with:
        name: BLUESPAWNHuntResults-${{ matrix.buildarch }}-${{ matrix.buildtype }}.xml
        path: BLUESPAWNHuntResults.xml
